name: Check Runner Specs

on: [workflow_dispatch]

jobs:
  print-specs:
    runs-on: ubuntu-latest
    steps:
      - name: CPU Information
        run: lscpu

      - name: Memory (RAM) Information
        run: free -h

      - name: Disk Space Information
        run: df -h
